In [1]:
import pandas as pd
import requests as requests

In [2]:
#url = "https://api-sdp.nwslsoccer.com/v1/nwsl/football/seasons/nwsl::Football_Season::0b6761e4701749f593690c0f338da74c/stats/players?locale=en-US&category=general&role=all&direction=desc&page=1&pageNumElement=400"

url = "https://api-sdp.nwslsoccer.com/v1/nwsl/football/seasons/nwsl::Football_Season::fad050beee834db88fa9f2eb28ce5a5c/stats/players?locale=en-US&category=general&role=all&direction=desc&page=1&pageNumElement=400"

session = requests.Session()
response = session.get(url)

data = response.json()

In [3]:
df = pd.json_normalize(data["players"])
df = df.explode("stats")
print(df.columns)

Index(['stats', 'rankLabel', 'playerId', 'providerId', 'bibNumber',
       'roleLabel', 'role', 'mediaFirstName', 'mediaLastName', 'shirtName',
       'shortName', 'displayName', 'nationality', 'nationalityIsoCode',
       'apiCallRequestTime', 'team.teamId', 'team.providerId',
       'team.shortName', 'team.officialName', 'team.acronymName',
       'team.acronymNameLocalized', 'team.isTeamFake', 'team.mediaName',
       'team.mediaShortName', 'team.countryCode', 'team.teamType',
       'team.overallSummary', 'team.stadium', 'team.allSeasonImagery',
       'team.editorial.social.facebook', 'team.editorial.social.instagram',
       'team.editorial.social.x', 'team.editorial.social.tikTok',
       'team.editorial.social.youTube', 'team.editorial.social.linkedIn',
       'team.editorial.websiteUrl', 'team.editorial.shopUrl',
       'team.editorial.ticketsUrl', 'team.editorial.clubPrimaryColour',
       'team.editorial.clubSecondaryColour', 'team.editorial.clubTextColour',
       'editorial.playerRoleWithinTeam'],
      dtype='str')

In [4]:
# Cleaning Data
# Turning Unstructured to Structured data

stats = pd.json_normalize(df["stats"])
df = pd.concat([df.drop(columns=["stats"]), stats], axis=1)
print(df.columns)

Index(['rankLabel', 'playerId', 'providerId', 'bibNumber', 'roleLabel', 'role',
       'mediaFirstName', 'mediaLastName', 'shirtName', 'shortName',
       'displayName', 'nationality', 'nationalityIsoCode',
       'apiCallRequestTime', 'team.teamId', 'team.providerId',
       'team.shortName', 'team.officialName', 'team.acronymName',
       'team.acronymNameLocalized', 'team.isTeamFake', 'team.mediaName',
       'team.mediaShortName', 'team.countryCode', 'team.teamType',
       'team.overallSummary', 'team.stadium', 'team.allSeasonImagery',
       'team.editorial.social.facebook', 'team.editorial.social.instagram',
       'team.editorial.social.x', 'team.editorial.social.tikTok',
       'team.editorial.social.youTube', 'team.editorial.social.linkedIn',
       'team.editorial.websiteUrl', 'team.editorial.shopUrl',
       'team.editorial.ticketsUrl', 'team.editorial.clubPrimaryColour',
       'team.editorial.clubSecondaryColour', 'team.editorial.clubTextColour',
       'editorial.playerRoleWithinTeam', 'statsId', 'statsLabel',
       'statsLabelAbbreviation', 'statsValue', 'statsUnit',
       'statsUnitAbbreviation'],
      dtype='str')

In [5]:
print(df.head(5))

  rankLabel                                           playerId  \
0      None  nwsl::Football_Player::4cb80ed654ff46e89167791...
0      None  nwsl::Football_Player::4cb80ed654ff46e89167791...
0      None  nwsl::Football_Player::4cb80ed654ff46e89167791...
0      None  nwsl::Football_Player::4cb80ed654ff46e89167791...
0      None  nwsl::Football_Player::4cb80ed654ff46e89167791...

                              providerId bibNumber   roleLabel  role  \
0  opta:Player:3sgg664ay83kxhe17ogbke978        20  Midfielder     3
0  opta:Player:3sgg664ay83kxhe17ogbke978        20  Midfielder     3
0  opta:Player:3sgg664ay83kxhe17ogbke978        20  Midfielder     3
0  opta:Player:3sgg664ay83kxhe17ogbke978        20  Midfielder     3
0  opta:Player:3sgg664ay83kxhe17ogbke978        20  Midfielder     3

  mediaFirstName mediaLastName shirtName shortName  ...  \
0          Julie         Doyle            J. Doyle  ...
0          Julie         Doyle            J. Doyle  ...
0          Julie         Doyle            J. Doyle  ...
0          Julie         Doyle            J. Doyle  ...
0          Julie         Doyle            J. Doyle  ...

  team.editorial.clubPrimaryColour team.editorial.clubSecondaryColour  \
0
0
0
0
0

  team.editorial.clubTextColour editorial.playerRoleWithinTeam  \
0
0
0
0
0

                  statsId              statsLabel statsLabelAbbreviation  \
0            games-played            Games played                     GP
0          minutes-played          Minutes played                   Mins
0                   goals                   Goals                      G
0                 assists                 Assists                      A
0  total-scoring-attempts  Total scoring attempts                      S

  statsValue statsUnit statsUnitAbbreviation
0       13.0       NaN                   NaN
0      528.0   minutes                     '
0        1.0       NaN                   NaN
0        2.0       NaN                   NaN
0        4.0       NaN                   NaN

[5 rows x 47 columns]

In [6]:
df_final = df.pivot_table(
    index="playerId",
    columns="statsLabel",
    values="statsValue"
).reset_index()
print(df_final.columns)

Index(['playerId', 'Accurate pass percentage', 'Aerial Duels',
       'Aerial Duels Won Percentage', 'Aerial Duels lost', 'Aerial Duels won',
       'Aerials Won Percentage', 'Appearances', 'Assists',
       'Assists (Intentional)',
       ...
       'Unsuccessful Passes Own Half', 'Unsuccessful Short Passes',
       'Unsuccessful lay-offs', 'Winning Goal', 'XGEfficiency', 'Xg',
       'Yellow Cards', 'Yellow Red Cards', 'Yellow cards', 'corners'],
      dtype='str', name='statsLabel', length=174)

In [7]:

print(df_final.head(5))

statsLabel                                           playerId  \
0           nwsl::Football_Player::0021a2896ee54ef191fb324...
1           nwsl::Football_Player::01429efe66554be8bc7f86e...
2           nwsl::Football_Player::021370e22b6846a48f5e988...
3           nwsl::Football_Player::0441c191624b4049911e4bb...
4           nwsl::Football_Player::04a1aad603eb46dd9c349c2...

statsLabel  Accurate pass percentage  Aerial Duels  \
0                               61.0          31.0
1                               75.0          27.0
2                               84.0          27.0
3                               69.0           6.0
4                               68.0          36.0

statsLabel  Aerial Duels Won Percentage  Aerial Duels lost  Aerial Duels won  \
0                                 54.84               14.0              17.0
1                                 59.26               11.0              16.0
2                                 77.78                6.0              21.0
3                                 33.33                4.0               2.0
4                                 44.44               20.0              16.0

statsLabel  Aerials Won Percentage  Appearances  Assists  \
0                              0.0         16.0      1.0
1                              0.0         22.0      1.0
2                              0.0         14.0      0.0
3                              0.0          3.0      0.0
4                              0.0         27.0      6.0

statsLabel  Assists (Intentional)  ...  Unsuccessful Passes Own Half  \
0                             1.0  ...                           5.0
1                             1.0  ...                          42.0
2                             NaN  ...                          26.0
3                             NaN  ...                           1.0
4                             6.0  ...                          97.0

statsLabel  Unsuccessful Short Passes  Unsuccessful lay-offs  Winning Goal  \
0                                64.0                    NaN           3.0
1                                75.0                    NaN           1.0
2                                37.0                    NaN           0.0
3                                 5.0                    NaN           0.0
4                               180.0                    1.0           1.0

statsLabel  XGEfficiency   Xg  Yellow Cards  Yellow Red Cards  Yellow cards  \
0                    0.0  0.0           3.0               0.0           3.0
1                    0.0  0.0           1.0               0.0           1.0
2                    0.0  0.0           4.0               0.0           4.0
3                    0.0  0.0           NaN               0.0           0.0
4                    0.0  0.0           1.0               0.0           1.0

statsLabel  corners
0               0.0
1               0.0
2               0.0
3               0.0
4              55.0

[5 rows x 174 columns]

In [8]:
df = pd.merge(df.drop(columns=['statsId', 'statsLabel',
       'statsLabelAbbreviation', 'statsValue', 'statsUnit',
       'statsUnitAbbreviation']), df_final, on="playerId")
df = df.drop_duplicates(["playerId"]).reset_index(drop=True)
print(df.columns)

Index(['rankLabel', 'playerId', 'providerId', 'bibNumber', 'roleLabel', 'role',
       'mediaFirstName', 'mediaLastName', 'shirtName', 'shortName',
       ...
       'Unsuccessful Passes Own Half', 'Unsuccessful Short Passes',
       'Unsuccessful lay-offs', 'Winning Goal', 'XGEfficiency', 'Xg',
       'Yellow Cards', 'Yellow Red Cards', 'Yellow cards', 'corners'],
      dtype='str', length=214)

In [9]:
print(df.head(5))

  rankLabel                                           playerId  \
0      None  nwsl::Football_Player::4cb80ed654ff46e89167791...
1      None  nwsl::Football_Player::a86e9ba2f4c44ce789c593b...
2      None  nwsl::Football_Player::ff16e70c73b943e38662bc6...
3      None  nwsl::Football_Player::0021a2896ee54ef191fb324...
4      None  nwsl::Football_Player::021370e22b6846a48f5e988...

                              providerId bibNumber   roleLabel  role  \
0  opta:Player:3sgg664ay83kxhe17ogbke978        20  Midfielder     3
1  opta:Player:d9dirjpaqkq3gga2zyeykcv6d         1  Goalkeeper     1
2  opta:Player:9yvkpwm78jaqr321imfc3rrbo         6    Defender     2
3  opta:Player:e2obgph6szyo04em3qr94g1qt        22     Forward     4
4  opta:Player:bilgoekg6gqwr3qbp6dp0j1zp         4    Defender     2

   mediaFirstName   mediaLastName     shirtName     shortName  ...  \
0           Julie           Doyle                    J. Doyle  ...
1          Aubrey       Kingsbury                A. Kingsbury  ...
2           Emily            Sams                     E. Sams  ...
3          Barbra           Banda  Barbra Banda      B. Banda  ...
4  Rafaelle Leone  Carvalho Souza      Rafaelle      Rafaelle  ...

  Unsuccessful Passes Own Half Unsuccessful Short Passes  \
0                          8.0                      32.0
1                         90.0                      16.0
2                         57.0                     115.0
3                          5.0                      64.0
4                         26.0                      37.0

  Unsuccessful lay-offs Winning Goal XGEfficiency   Xg Yellow Cards  \
0                   NaN          0.0          0.0  0.0          NaN
1                   NaN          0.0          0.0  0.0          NaN
2                   NaN          0.0          0.0  0.0          2.0
3                   NaN          3.0          0.0  0.0          3.0
4                   NaN          0.0          0.0  0.0          4.0

  Yellow Red Cards Yellow cards corners
0              0.0          0.0     1.0
1              0.0          0.0     0.0
2              0.0          2.0     0.0
3              0.0          3.0     0.0
4              0.0          4.0     0.0

[5 rows x 214 columns]

In [10]:
##QC

In [11]:
print(df.shape)

(400, 214)

In [12]:
df.loc[df["playerId"].isnull()==True]

Empty DataFrame
Columns: [rankLabel, playerId, providerId, bibNumber, roleLabel, role, mediaFirstName, mediaLastName, shirtName, shortName, displayName, nationality, nationalityIsoCode, apiCallRequestTime, team.teamId, team.providerId, team.shortName, team.officialName, team.acronymName, team.acronymNameLocalized, team.isTeamFake, team.mediaName, team.mediaShortName, team.countryCode, team.teamType, team.overallSummary, team.stadium, team.allSeasonImagery, team.editorial.social.facebook, team.editorial.social.instagram, team.editorial.social.x, team.editorial.social.tikTok, team.editorial.social.youTube, team.editorial.social.linkedIn, team.editorial.websiteUrl, team.editorial.shopUrl, team.editorial.ticketsUrl, team.editorial.clubPrimaryColour, team.editorial.clubSecondaryColour, team.editorial.clubTextColour, editorial.playerRoleWithinTeam, Accurate pass percentage, Aerial Duels, Aerial Duels Won Percentage, Aerial Duels lost, Aerial Duels won, Aerials Won Percentage, Appearances, Assists, Assists (Intentional), Attempts from Set Pieces, Average Distance Covered, Average Distance Covered High Intensity Running, Average Distance Covered Jogging, Average Distance Covered Low Intensity Running, Average Distance Covered Sprinting, Average Distance Covered Walking, Away Goals, Backward Passes, Blocked Shots, Blocks, Carries, Catches, Clean Sheets, Clearances Off the Line, Corners Taken (incl short corners), Corners Won, Cross Complete Percentage, Crosses not Claimed, Direct Setpiece Goals, Drops, Duels, Duels Won Percentage, Duels lost, Duels won, Final Third Touches, Forward Passes, Foul Attempted Tackle, Foul Won Penalty, Fouls committed, Fouls suffered, GK Successful Distribution, GK Unsuccessful Distribution, Games Played, Games played, Goal Assists, Goal Kicks, Goalkeeper Smother, Goals, Goals Conceded, Goals Conceded Inside Box, Goals Conceded Outside Box, Goals Free kick, Goals Involvements, Goals Openplay, Goals against average, Goals conceded, Goals from Inside Box, Goals from Outside Box, Ground Duels, ...]
Index: []

[0 rows x 214 columns]

In [13]:
df.loc[df["shortName"].isnull()==True]

Empty DataFrame
Columns: [rankLabel, playerId, providerId, bibNumber, roleLabel, role, mediaFirstName, mediaLastName, shirtName, shortName, displayName, nationality, nationalityIsoCode, apiCallRequestTime, team.teamId, team.providerId, team.shortName, team.officialName, team.acronymName, team.acronymNameLocalized, team.isTeamFake, team.mediaName, team.mediaShortName, team.countryCode, team.teamType, team.overallSummary, team.stadium, team.allSeasonImagery, team.editorial.social.facebook, team.editorial.social.instagram, team.editorial.social.x, team.editorial.social.tikTok, team.editorial.social.youTube, team.editorial.social.linkedIn, team.editorial.websiteUrl, team.editorial.shopUrl, team.editorial.ticketsUrl, team.editorial.clubPrimaryColour, team.editorial.clubSecondaryColour, team.editorial.clubTextColour, editorial.playerRoleWithinTeam, Accurate pass percentage, Aerial Duels, Aerial Duels Won Percentage, Aerial Duels lost, Aerial Duels won, Aerials Won Percentage, Appearances, Assists, Assists (Intentional), Attempts from Set Pieces, Average Distance Covered, Average Distance Covered High Intensity Running, Average Distance Covered Jogging, Average Distance Covered Low Intensity Running, Average Distance Covered Sprinting, Average Distance Covered Walking, Away Goals, Backward Passes, Blocked Shots, Blocks, Carries, Catches, Clean Sheets, Clearances Off the Line, Corners Taken (incl short corners), Corners Won, Cross Complete Percentage, Crosses not Claimed, Direct Setpiece Goals, Drops, Duels, Duels Won Percentage, Duels lost, Duels won, Final Third Touches, Forward Passes, Foul Attempted Tackle, Foul Won Penalty, Fouls committed, Fouls suffered, GK Successful Distribution, GK Unsuccessful Distribution, Games Played, Games played, Goal Assists, Goal Kicks, Goalkeeper Smother, Goals, Goals Conceded, Goals Conceded Inside Box, Goals Conceded Outside Box, Goals Free kick, Goals Involvements, Goals Openplay, Goals against average, Goals conceded, Goals from Inside Box, Goals from Outside Box, Ground Duels, ...]
Index: []

[0 rows x 214 columns]

In [14]:
df_test = df[[
    "playerId","roleLabel","shortName" ,"nationality","team.officialName","Appearances","Games Played","Minutes played","Interceptions","Ground Duels", "Ground Duels won","Duels","Duels won","Aerial Duels","Aerial Duels won","Blocked Shots","Blocks","Foul Attempted Tackle","Times Tackled","Last Player Tackle","Total Clearances","Total Tackles","Tackles won","Accurate pass percentage","Backward Passes","Final Third Touches","Forward Passes","Overruns","Progressive Carries","Recoveries","Second Goal Assists","Successful Launches","Successful Long Passes","Successful Passes Opposition Half","Unsuccessful Launches","Unsuccessful Long Passes","Unsuccessful Passes Opposition Half","Total Big Chances Created","Key Passes (Attempt Assists)","Assists (Intentional)","Attempts from Set Pieces","Away Goals","Goals","Home Goals","Corners Taken (incl short corners)","Corners Won","corners","Goal Assists","On target scoring attempts","Total Shots","Shots On Target ( inc goals )","Total Big Chances Scored","Total attacking assists","Total scoring attempts","XGEfficiency","Xg"]]

In [15]:
print(df_test.head(5))

                                            playerId   roleLabel  \
0  nwsl::Football_Player::4cb80ed654ff46e89167791...  Midfielder
1  nwsl::Football_Player::a86e9ba2f4c44ce789c593b...  Goalkeeper
2  nwsl::Football_Player::ff16e70c73b943e38662bc6...    Defender
3  nwsl::Football_Player::0021a2896ee54ef191fb324...     Forward
4  nwsl::Football_Player::021370e22b6846a48f5e988...    Defender

      shortName nationality  team.officialName  Appearances  Games Played  \
0      J. Doyle         USA      Orlando Pride         13.0          13.0
1  A. Kingsbury         USA  Washington Spirit         28.0          28.0
2       E. Sams         USA      Orlando Pride         27.0          27.0
3      B. Banda      Zambia      Orlando Pride         16.0          16.0
4      Rafaelle      Brazil      Orlando Pride         14.0          14.0

   Minutes played  Interceptions  Ground Duels  ...  corners  Goal Assists  \
0           528.0            1.0          46.0  ...      1.0           2.0
1          2505.0            NaN           8.0  ...      0.0           NaN
2          2362.0           36.0         115.0  ...      0.0           NaN
3          1299.0            2.0         158.0  ...      0.0           1.0
4           993.0           17.0          44.0  ...      0.0           NaN

   On target scoring attempts  Total Shots  Shots On Target ( inc goals )  \
0                         2.0          4.0                            2.0
1                         0.0          NaN                            NaN
2                         1.0          2.0                            1.0
3                        35.0         58.0                           35.0
4                         1.0          5.0                            1.0

   Total Big Chances Scored  Total attacking assists  Total scoring attempts  \
0                       NaN                      2.0                     4.0
1                       NaN                      0.0                     0.0
2                       NaN                      0.0                     2.0
3                       5.0                      1.0                    58.0
4                       NaN                      0.0                     5.0

   XGEfficiency   Xg
0           0.0  0.0
1           0.0  0.0
2           0.0  0.0
3           0.0  0.0
4           0.0  0.0

[5 rows x 56 columns]

In [16]:
print(df_test["roleLabel"].unique())

<StringArray>
['Midfielder', 'Goalkeeper', 'Defender', 'Forward']
Length: 4, dtype: str

In [17]:
df_test = df_test.loc[df_test["roleLabel"]=='Defender']
print(df_test.head(5))

                                             playerId roleLabel  \
2   nwsl::Football_Player::ff16e70c73b943e38662bc6...  Defender
4   nwsl::Football_Player::021370e22b6846a48f5e988...  Defender
6   nwsl::Football_Player::521bad7c3a2f49a185c968f...  Defender
9   nwsl::Football_Player::f0a281901a6340798be863c...  Defender
15  nwsl::Football_Player::18d7e7320d2949b083c7315...  Defender

        shortName nationality  team.officialName  Appearances  Games Played  \
2         E. Sams         USA      Orlando Pride         27.0          27.0
4        Rafaelle      Brazil      Orlando Pride         14.0          14.0
6   H. McCutcheon         USA      Orlando Pride         28.0          28.0
9        K. Sylla      France  Washington Spirit         15.0          15.0
15      E. Morgan     England  Washington Spirit         28.0          28.0

    Minutes played  Interceptions  Ground Duels  ...  corners  Goal Assists  \
2           2362.0           36.0         115.0  ...      0.0           NaN
4            993.0           17.0          44.0  ...      0.0           NaN
6           2357.0           27.0         163.0  ...      0.0           4.0
9            394.0            3.0          31.0  ...      0.0           NaN
15          2256.0           22.0         102.0  ...      0.0           2.0

    On target scoring attempts  Total Shots  Shots On Target ( inc goals )  \
2                          1.0          2.0                            1.0
4                          1.0          5.0                            1.0
6                         10.0         28.0                           10.0
9                          0.0          NaN                            NaN
15                         5.0          7.0                            5.0

    Total Big Chances Scored  Total attacking assists  Total scoring attempts  \
2                        NaN                      0.0                     2.0
4                        NaN                      0.0                     5.0
6                        2.0                      4.0                    28.0
9                        NaN                      0.0                     0.0
15                       2.0                      2.0                     7.0

    XGEfficiency   Xg
2            0.0  0.0
4            0.0  0.0
6            0.0  0.0
9            0.0  0.0
15           0.0  0.0

[5 rows x 56 columns]

In [18]:
#Movement

In [19]:
movement = df_test[[
    "playerId","roleLabel","shortName" ,"nationality","team.officialName","Appearances","Games Played","Minutes played","Interceptions","Duels","Duels won","Blocked Shots","Blocks","Times Tackled","Last Player Tackle","Total Clearances","Total Tackles","Tackles won","Foul Attempted Tackle"]]

per90_col = ["Interceptions","Duels","Duels won","Blocked Shots","Blocks","Foul Attempted Tackle","Times Tackled","Last Player Tackle","Total Clearances","Total Tackles","Tackles won"]
for col in per90_col:
    movement[col + " per90"] = movement[col]/movement["Minutes played"]*90

print(movement.head(5))

                                             playerId roleLabel  \
2   nwsl::Football_Player::ff16e70c73b943e38662bc6...  Defender
4   nwsl::Football_Player::021370e22b6846a48f5e988...  Defender
6   nwsl::Football_Player::521bad7c3a2f49a185c968f...  Defender
9   nwsl::Football_Player::f0a281901a6340798be863c...  Defender
15  nwsl::Football_Player::18d7e7320d2949b083c7315...  Defender

        shortName nationality  team.officialName  Appearances  Games Played  \
2         E. Sams         USA      Orlando Pride         27.0          27.0
4        Rafaelle      Brazil      Orlando Pride         14.0          14.0
6   H. McCutcheon         USA      Orlando Pride         28.0          28.0
9        K. Sylla      France  Washington Spirit         15.0          15.0
15      E. Morgan     England  Washington Spirit         28.0          28.0

    Minutes played  Interceptions  Ground Duels  ...  Aerial Duels per90  \
2           2362.0           36.0         115.0  ...            1.181202
4            993.0           17.0          44.0  ...            2.447130
6           2357.0           27.0         163.0  ...            3.169283
9            394.0            3.0          31.0  ...            2.969543
15          2256.0           22.0         102.0  ...            1.356383

    Aerial Duels won per90  Blocked Shots per90  Blocks per90  \
2                 0.609653                  NaN      0.533446
4                 1.903323             0.271903      0.906344
6                 1.794654             0.381841      0.343657
9                 1.370558                  NaN      0.913706
15                0.837766             0.119681      0.877660

    Foul Attempted Tackle per90  Times Tackled per90  \
2                      0.190517             0.457240
4                      0.725076             0.543807
6                      0.687314             1.374629
9                      1.370558             0.456853
15                     0.239362             0.478723

    Last Player Tackle per90  Total Clearances per90  Total Tackles per90  \
2                        NaN                3.886537             1.752752
4                   0.090634                6.525680             1.359517
6                        NaN                1.871022             2.291048
9                        NaN                3.883249             1.827411
15                       NaN                3.829787             1.555851

    Tackles won per90
2            1.143099
4            0.815710
6            1.412813
9            1.598985
15           0.877660

[5 rows x 38 columns]

In [23]:
movement[["Times Tackled","Total Tackles","Tackles won"]]

     Times Tackled  Total Tackles  Tackles won
2             12.0           46.0         30.0
4              6.0           15.0          9.0
6             36.0           60.0         37.0
9              2.0            8.0          7.0
15            12.0           39.0         22.0
..             ...            ...          ...
383            1.0            3.0          1.0
384            1.0            6.0          4.0
385            2.0           10.0          6.0
390            9.0           25.0         14.0
397            NaN            NaN          0.0

[119 rows x 3 columns]